--
-- Drop existing objects
--

DROP SCHEMA IF EXISTS "provider" CASCADE;

--
-- Provider schema
--

CREATE SCHEMA IF NOT EXISTS "provider"; 

CREATE SEQUENCE "provider".asset_draft_id_seq INCREMENT 1 MINVALUE 1 START 1 CACHE 1;

CREATE TABLE "provider".asset_draft
(
  id                             integer                     NOT NULL  DEFAULT nextval('provider.asset_draft_id_seq'::regclass),
  "account"                      integer                     NOT NULL,
  -- Unique draft identifier. The key is also the business key of the publication workflow instance
  "key"                          uuid                        NOT NULL,
  -- Workflow definition and instance identifiers in case a workflow has started
  "process_definition"           character varying,
  "process_instance"             character varying,
  "title"                        character varying           NOT NULL,
  "version"                      character varying           NOT NULL,
  "data"                         character varying           NOT NULL,
  -- Draft asset unique identifier in catalogue
  "asset_draft"                  uuid                        NOT NULL,
  -- Published asset unique identifier in catalogue. The value is generated by the PID service
  "asset_published"              character varying,
  -- Draft status 
  "status"                       character varying (30)      NOT NULL,
  "helpdesk_rejection_reason"    character varying,
  "provider_rejection_reason"    character varying,
  "ingested"                     boolean                     NOT NULL,
  "source"                       character varying,
  "created_on"                   timestamp without time zone NOT NULL,
  "modified_on"                  timestamp without time zone NOT NULL,
  CONSTRAINT pk_asset_draft PRIMARY KEY (id),
  CONSTRAINT uq_asset_draft_key UNIQUE ("key"),
  CONSTRAINT fk_asset_draft_account FOREIGN KEY ("account")
      REFERENCES web.account ("id") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE INDEX idx_provider_asset_draft_key ON "provider".asset_draft USING btree ("key");
