--
-- Cleanup
--

DROP TABLE IF EXISTS "web"."account_client_request";
DROP TYPE IF EXISTS "web"."provider_workspace_type_t"; 
DROP TYPE IF EXISTS "web"."ows_service_type_t";

--
-- Create 
--

CREATE TYPE "web"."provider_workspace_type_t" 
    AS ENUM ('PUBLIC', 'PRIVATE');

CREATE TYPE "web"."ows_service_type_t"
    AS ENUM ('WMS', 'WMTS', 'WFS', 'TMS');

CREATE TABLE "web"."account_client_request"
(
    "request_id" char(32) NOT NULL,
    "recorded" timestamp NOT NULL,
    "client_id" uuid NOT NULL,
    "virtual_host" varchar(31) NOT NULL,
    "uri" varchar NOT NULL,
    "workspace_type" "web"."provider_workspace_type_t" NULL,
    "workspace_provider_key" uuid NULL,
    "ows_service_type" "web"."ows_service_type_t" NULL,
    "ows_service_version" varchar(12) NULL,
    "ows_request" varchar(31) NULL,
    "asset_keys" varchar(255) NULL,
    "started" timestamp NULL,
    "took" integer NULL,
    "response_size" integer NULL
) 
PARTITION BY RANGE ("recorded");


COMMENT ON COLUMN "web"."account_client_request"."request_id" IS 
    'identifier generated by ingress (128bit as hex string)';
COMMENT ON COLUMN "web"."account_client_request"."recorded" IS 
    'when this request was recorded by auth-subrequest service';
COMMENT ON COLUMN "web"."account_client_request"."client_id" IS 
    'identifier of the client that carried out this request';
COMMENT ON COLUMN "web"."account_client_request"."uri" IS 
    'the auth-request-redirect URI passed to auth-subrequest by the ingress controller';
COMMENT ON COLUMN "web"."account_client_request"."virtual_host" IS
    'the virtual host of the original request URL';
COMMENT ON COLUMN "web"."account_client_request"."asset_keys" IS 
    'a comma-separated list of keys of assets read by this request';
COMMENT ON COLUMN "web"."account_client_request"."started" IS 
    'when this request was received by the ingress controller';
COMMENT ON COLUMN "web"."account_client_request"."took" IS 
    'processing time for this request (millis)';
COMMENT ON COLUMN "web"."account_client_request"."response_size" 
    IS 'response size (in bytes)';


CREATE TABLE "web"."account_client_request_Y2022_Q4" PARTITION OF "web"."account_client_request"
    FOR VALUES FROM ('2022-10-01T00:00:00Z') TO ('2023-01-01T00:00:00Z');
ALTER TABLE "web"."account_client_request_Y2022_Q4" ADD CONSTRAINT "fk_account_client_request_Y2022_Q4_client" 
    FOREIGN KEY (client_id) REFERENCES "web"."account_client" ("client_id");
CREATE UNIQUE INDEX ON "web"."account_client_request_Y2022_Q4" ("request_id");
CREATE INDEX ON "web"."account_client_request_Y2022_Q4" ("client_id");
CREATE INDEX ON "web"."account_client_request_Y2022_Q4" ("recorded"); 

CREATE TABLE "web"."account_client_request_Y2023_Q1" PARTITION OF "web"."account_client_request"
    FOR VALUES FROM ('2023-01-01T00:00:00Z') TO ('2023-04-01T00:00:00Z');
ALTER TABLE "web"."account_client_request_Y2023_Q1" ADD CONSTRAINT "fk_account_client_request_Y2023_Q1_client" 
    FOREIGN KEY (client_id) REFERENCES "web"."account_client" ("client_id");
CREATE UNIQUE INDEX ON "web"."account_client_request_Y2023_Q1" ("request_id");
CREATE INDEX ON "web"."account_client_request_Y2023_Q1" ("client_id");
CREATE INDEX ON "web"."account_client_request_Y2023_Q1" ("recorded"); 

CREATE TABLE "web"."account_client_request_Y2023_Q2" PARTITION OF "web"."account_client_request"
    FOR VALUES FROM ('2023-04-01T00:00:00Z') TO ('2023-07-01T00:00:00Z');
ALTER TABLE "web"."account_client_request_Y2023_Q2" ADD CONSTRAINT "fk_account_client_request_Y2023_Q2_client" 
    FOREIGN KEY (client_id) REFERENCES "web"."account_client" ("client_id");
CREATE UNIQUE INDEX ON "web"."account_client_request_Y2023_Q2" ("request_id");
CREATE INDEX ON "web"."account_client_request_Y2023_Q2" ("client_id");
CREATE INDEX ON "web"."account_client_request_Y2023_Q2" ("recorded"); 

CREATE TABLE "web"."account_client_request_Y2023_Q3" PARTITION OF "web"."account_client_request"
    FOR VALUES FROM ('2023-07-01T00:00:00Z') TO ('2023-10-01T00:00:00Z');
ALTER TABLE "web"."account_client_request_Y2023_Q3" ADD CONSTRAINT "fk_account_client_request_Y2023_Q3_client" 
    FOREIGN KEY (client_id) REFERENCES "web"."account_client" ("client_id");
CREATE UNIQUE INDEX ON "web"."account_client_request_Y2023_Q3" ("request_id");
CREATE INDEX ON "web"."account_client_request_Y2023_Q3" ("client_id");
CREATE INDEX ON "web"."account_client_request_Y2023_Q3" ("recorded"); 

