ALTER TABLE "order".order_status_hist DROP CONSTRAINT IF EXISTS chk_order_status_hist_status_enum;

ALTER TABLE "order".order_status_hist ADD CONSTRAINT chk_order_status_hist_status_enum CHECK
  ("status" IN (
    'CREATED',
    'PENDING_PROVIDER_APPROVAL' ,'PROVIDER_REJECTED', 'PROVIDER_ACCEPTED',
    'PENDING_PROVIDER_CONTRACT_UPLOAD', 'PENDING_CONSUMER_CONTRACT_ACCEPTANCE', 'CONTRACT_IS_SIGNED',
    'CHARGED',
    'PENDING_PROVIDER_SEND_CONFIRMATION', 'PENDING_CONSUMER_RECEIVE_CONFIRMATION', 'ASSET_REGISTRATION',
    'CANCELLED', 'REFUNDED', 'SUCCEEDED'
  ));

ALTER TABLE "order".order DROP CONSTRAINT IF EXISTS chk_order_status_enum;

ALTER TABLE "order".order ADD CONSTRAINT chk_order_status_enum CHECK
  ("status" IN (
    'CREATED',
    'PENDING_PROVIDER_APPROVAL' ,'PROVIDER_REJECTED', 'PROVIDER_ACCEPTED',
    'PENDING_PROVIDER_CONTRACT_UPLOAD', 'PENDING_CONSUMER_CONTRACT_ACCEPTANCE', 'CONTRACT_IS_SIGNED',
    'CHARGED',
    'PENDING_PROVIDER_SEND_CONFIRMATION', 'PENDING_CONSUMER_RECEIVE_CONFIRMATION', 'ASSET_REGISTRATION',
    'CANCELLED', 'REFUNDED', 'SUCCEEDED'
  ));
